development: &default
  adapter: mysql2
  encoding: utf8
  database: jasonl_biz_development
  host: 54.250.144.204
  username: jasonl
  password: jasonl

test: &TEST
  <<: *default
  database: jasonl_biz_test

production: &PROD
  <<: *default
  database: jasonl_biz_development