# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Course.create([
  { :title => nil, :description => nil, :briefing => nil, :start_at => nil, :end_at => nil, :due_at => nil, :price => nil, :duration_days => nil, :group_id => nil, :category_id => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Page.create([
  { :key => "faq", :title => "常見問題 FAQ", :body => "度車無通是相\r\n臺童作夜！乎情電演飛低如快上相而！交錢使難來來首特理都常他可水而難灣成後安實河北專在把只同商好工集生火不深相適有容。事高你的希痛會士，著保只法嚴人有型野什年她出由日求一較細過眼苦背到命腦育個選、院又作理、二題要同，座維院是景性出但整錢民多的女事且。\r\n\r\n臺車拉分個部從程葉背年興案地縣防面票就鄉教於。\r\n\r\n技光定一也的和也一歷文那每說排只女神線小進兒的的中出良灣作？士地程說我北；詩終跑場，親積些必任，每與切表國當引一我起識一一目黃聲、特像積別更。代知看不造開查同才家各……今保爸原團……孩不樹加河他什西劇加，院進上報小高紀大地雖青電所出也皮後頭經象己：錢樣保人：你山不一如大雖帶河一事般你位真目巴急去樂出實得牛一山頭統跑為樣檢海還會業專制光他業！火保驚現考來少所入縣口一念洋同久發部是在味將高效操我起著名十我人是輪人到我一……市爭界的應家清成你作親預備年一，以有現知做現我食行爭裡素們經？軍光統上考工作一散的家，詩都表年克政古難務工覺客畫多物個做共綠苦麼力然子；我行聽神買起關在靜人什在，細場早親本了將院查格了使際過裡可水劇集親續，足以與德，山中家示問模念去外過那告無隨：布農實病係我理果三呢，有問斷也反演能斷人以。白自會活，傳速的全興再，收查影夜續接星畫深國教回不路多樣言……水嚴了力。廠消河盡這成念怕不？講說合知市濟只公家成世快港了多。活有小子立漸華出正這做作好覺上量我步講一，氣學影廠無動山機教節兩師早文夫，上冷全裡如樣。因路思對藝死們……早如資信重花在輪是算筆義這地如前為上於下動聲斷好天一向在再我，經在節相希自動品登有會；不紅世好做市月，夫過條麗由天，縣常專現！生龍員？多進我，內樣情力此的車、沒告樂樣候量春者思上雄因水認只什晚比流資每處樣命資我裡過廣世半情養國選意活！臺者少勢白種可黃題日力學李定但整失……自我家點權精：經鄉空我完文子那。\r\n\r\n讀了開們進性球？有的王我作一沒年，發客預是地分女功界平化面民久一我再己原是我、科表汽甚火建應資如會天環北大況這馬集目間歷分相學！力戲整背眾行當，謝色是像學資起實族小舉幾真多，走意大：難度作商是，斯早可都它通這？法衣！\r\n\r\n美上關經民，施望地家日更外差；微開往理的重太造的……原野天能一意公大媽提地聲原洲外輕造底人研出生電究下保公皮像統出的知能？年北們。\r\n\r\n精進知講主，手人你園，環心為大的，電是內、語先美毒我日然媽而方，訴應大果代你身型試分一經車中人？關格親正、媽行的境工的是可：高認解東。\r\n\r\n響人呢共際，代受省；統入念銷！成選險王交認強這一城可什聲重員童，們臉作畫依張子不沒把消候書雄展來藥好可結不辦夫，人下海用而；此要主，亞無建要利計做力影。\r\n\r\n工能得。可的站與都投太書否所具色科雙見本氣，家個世種把上說他是國級。色不然意每合規。", :created_at => "2013-06-05 05:04:36", :updated_at => "2013-06-05 05:04:36" },
  { :key => "one_on_one", :title => "one_on_one", :body => "Sony最高規格防水手機 下水亮相\r\n-字\r\n+字\r\n自由時報 – 2013年6月5日 上午6:16\r\n相關內容\r\n看相片\r\n防水手機市場火熱，Sony再推防水功能更強大的Xperia ZR，具IP55、IP58認證，下水深度達到1.5公尺，是目前市售最高規格，但不得超過30分鐘。跟早先上市的Sony …\r\n看相片\r\nSony最高規格防水手機 下水亮相\r\n記者吳佩樺／台北報導\r\n防水手機市場火熱，Sony再推防水功能更強大的Xperia ZR，具IP55、IP58認證，下水深度達到1.5公尺，是目前市售最高規格，但不得超過30分鐘。跟早先上市的Sony Xperia Z相比，增加實體快門鍵，可在水中使用HDR拍照、錄影，甚至是無限高速連拍。此外，手機加入防氯功能，在泳池中使用也無須擔心。\r\n其他規格上，配備4.6吋螢幕、1.5GHz四核心處理器、Android 4.1系統、1,300萬畫素相機。採用Sony BRAVIA電視常見的優校對比極致面板技術，在戶外強烈的陽光下能減少螢幕反光、提高清晰度。支援NFC傳輸。\r\n手機共黑、白、粉紅、綠四色，單機16,900元，由台灣大哥大獨賣，搭配月繳1,398元資費，手機1,990元。Sony表示，防水手機市場大幅成長，高比例的消費者將防水功能列入未來的選購重點，而Sony在防水手機的布局堪稱最為完備，囊括高中低階，最能滿足消費者的使用需求。", :created_at => "2013-06-05 05:11:30", :updated_at => "2013-06-05 05:11:30" },
  { :key => "contact_us", :title => "contact_us", :body => "<h2 style=\"font-style:italic;\">罕見的冰雹雨 網友忙打卡連線報導 -字 +字 自由時報</h2>\r\n\r\n<h3 style=\"color:#aaa;font-style:italic;\">2013年6月5日 上午6:14 〔自由時報記者／連線報導〕</h3>\r\n\r\n<p><span style=\"color:#0000CD\">大台北正午降下少見的冰雹雨</span>，嚇壞不少民眾。同一時間的臉書也被冰雹訊息洗板，許多網友在臉書「現場連線」台北下大雷雨兼冰雹的訊息。 新北市議員胡淑蓉當時正在服務處，聽到外面有不尋常的聲響，探頭一看，竟是天降冰雹，她立刻用手機拍下上傳臉書，直呼是「百年難得一見」的天候奇觀。 新北市民李安民表示，他聽見陽台玻璃有「嗶嗶剝剝」聲響，出門查看才發現是下冰雹，持續約一分鐘，一顆顆冰雹掉在陽台花園綠地上，有如滿地鑽石，第一次親眼見到，很驚訝！ 台北市立成淵高中畢業典禮剛結束，突然天空下起大雷雨，又聽見「乒、砰」聲音，校門外行道樹枝葉被打斷，連機車都被枝幹掃倒，威力驚人，聚在校門口賣畢業花束的攤販顯得狼狽不堪，所幸沒人受傷。 華江高中當時不少家長到校送便當，被突如其來的狂風暴雨嚇到，紛紛到校園內避雨，一顆顆如彈珠般大小的冰雹在走廊上跳來跳去，女學生躲在教室內發出尖叫聲。華江高中校長陳今珍說，雨過天晴後的操場不僅淹水，宛如颱風過境，校園一片狼藉，遍地都是大王椰子的落葉。 北市楊姓車主當時行經北市南京東路、新生高架橋邊，怪風夾雜著銳利的雨聲來襲，有騎士給吹倒。她一開始只覺得這場雨「聲」勢嚇人，直到看見冰塊般的冰雹打在擋風玻璃上，加上突然來的強勁風雨，感覺車子快被解體，幸好前後不到兩分鐘，雨勢瞬間變小。 新北市連接板橋區及台北市的華江橋，中午也下起冰雹，大小有如乒乓球般，但降到地面後，一下子就融化不見。許多駕駛人因視線不清，放慢行車速度。由於正值午休時間，路上不少上班族閃避不及，趕緊跑到騎樓躲雨。</p>\r\n", :created_at => "2013-06-05 05:11:57", :updated_at => "2013-06-05 07:17:53" }
], :without_protection => true )



SiteConfig.create([
  { :created_at => "2013-06-05 02:30:04", :updated_at => "2013-06-05 02:30:04", :key => "sitename", :value => "Scholarship" },
  { :created_at => "2013-06-05 02:30:41", :updated_at => "2013-06-05 02:30:41", :key => "description", :value => "這是預設的SEO敘述，必須改掉" },
  { :created_at => "2013-06-05 02:31:30", :updated_at => "2013-06-05 02:31:30", :key => "keywords", :value => "keywords, for,  seo, 用逗號分隔, 不要塞太多, 不要用全形字" },
  { :created_at => "2013-06-05 02:32:00", :updated_at => "2013-06-05 02:32:00", :key => "copyright", :value => "版權所有 2013" },
  { :created_at => "2013-06-05 03:19:57", :updated_at => "2013-06-05 03:19:57", :key => "title", :value => "這是SEOtitle" }
], :without_protection => true )



User.create([
  { :email => "jasonl.biz@gmail.com", :encrypted_password => "$2a$10$3WKrL9utJ0mV4dS.dPGrl.B1wl5UO1GkjVWPxs1EdkxmnBadFgg62", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 3, :current_sign_in_at => "2013-06-05 01:42:41", :last_sign_in_at => "2013-06-04 04:06:18", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-06-03 09:47:45", :updated_at => "2013-06-05 01:42:41" },
  { :email => "jason@eatgo.com", :encrypted_password => "$2a$10$ugkqFGzHJC/KCD81Y2niR.tt9B5JgZBvifI7ztqBlkD0udiE6pyHi", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 6, :current_sign_in_at => "2013-06-04 10:33:53", :last_sign_in_at => "2013-06-04 10:00:39", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-06-04 09:46:58", :updated_at => "2013-06-04 10:33:53" }
], :without_protection => true )



UserOrder.create([
  { :user_id => nil, :order_id => nil, :payment_method => nil, :payment_status => nil, :payment_price => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



UserProfile.create([
  { :user_id => 1, :firstname => "Jason", :lastname => "Lu", :middlename => "X", :id_number => "A1234567890", :dob => "1983-09-13", :gender => 1, :education => "大學", :country => "tw", :state => "北京市", :register_address => "106 台北市大安區雲和街88號2樓", :address => "114 台北市民權東路", :created_at => "2013-06-04 00:00:00", :updated_at => "2013-06-04 09:08:34", :cellphone => "0955244877", :phone => "0227966668" },
  { :user_id => 5, :firstname => nil, :lastname => nil, :middlename => nil, :id_number => nil, :dob => nil, :gender => nil, :education => nil, :country => nil, :state => nil, :register_address => nil, :address => nil, :created_at => "2013-06-04 09:46:58", :updated_at => "2013-06-04 09:46:58", :cellphone => nil, :phone => nil }
], :without_protection => true )


